version: '2'
services:
  webfinderapp-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/WebFinderApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=WebFinderApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
